In [1]:
import pandas as pd

In [2]:
# memberId = pd.read_clipboard()
# memberId.to_csv("memberIDs.csv", index = False)

In [3]:
memberID = pd.read_csv('memberIDs.csv')
chairs = pd.read_csv('consolidated_Chairs.csv')
ranking = pd.read_csv('consolidated_Ranking.csv')

In [4]:
# some problem accessing Member column checking to see if hidden spaces
# fixed with renaming cols
# for cols in memberID:
#     print(len(cols))
#     print(cols)

In [5]:
memberID.columns=['All Data', 'Member_ID']

In [6]:
memberID

                                           All Data Member_ID
0         Abdnor, James (Republican - South Dakota)   A000009
1           Abercrombie, Neil (Democratic - Hawaii)   A000014
2       Abourezk, James (Democratic - South Dakota)   A000017
3       Abraham, Ralph Lee (Republican - Louisiana)   A000374
4          Abraham, Spencer (Republican - Michigan)   A000355
...                                             ...       ...
2350          Zinke, Ryan K. (Republican - Montana)   Z000018
2351          Zion, Roger H. (Republican - Indiana)   Z000010
2352       Zorinsky, Edward (Democratic - Nebraska)   Z000013
2353  Zschau, Edwin V. W. (Republican - California)   Z000014
2354        Zwach, John M. (Republican - Minnesota)   Z000016

[2355 rows x 2 columns]

In [7]:
#Slicing party middle inital and state for cleaning
splitSpace = []
for i in memberID['All Data']:
    splitSpace.append(i.split())

In [8]:
#Getting First and Last Name
lastName1 = []
firstName1 =[]
for i in splitSpace:
    lastName1.append(i[0][:-1])
    firstName1.append(i[1])
memberID['First_Name'] = firstName1
memberID['Last_Name'] = lastName1

In [9]:
partyState = []
for i in splitSpace:
    if len(i) > 5:
        partyState.append(i[-4:])
    else:
        partyState.append(i[-3:])
party =[]
middleI = []
messyState = []
for i in partyState:
    if len(i) >= 4:
        middleI.append(i[:2])
        messyState.append(i[-2:])
        if i[0] == '(Democratic' or i[0] == '(Republican':
            party.append(i[0])
        else:
            party.append(i[1])
    else:
        middleI.append('NaN')
        party.append(i[0])
        messyState.append(i[-2:])

In [10]:
# Cleaning up party
party1 = []
for i in party:
    party1.append(i[1:])
print(party1[:10])
memberID['Party'] = party1

['Republican', 'Democratic', 'Democratic', 'Republican', 'Republican', 'Democratic', 'Democratic', 'Democratic', 'Democratic', 'Democratic']

In [11]:
#Cleaning up middle initial adding NaNs when necessary
#This might be weird if there are two middle names
#be sure to inspect data
# print(len(middleI))
# print(middleI[:10])
middleI1 = []
for i in middleI:
    middleI1.append(i)
middleI2 =[]
for i in middleI1:
    if i == 'NaN':
        middleI2.append(i)
    else:
        middleI2.append(i[0])
middleI3 = []
for i in middleI2:
    if i == '(Republican' or i == '(Democratic':
        middleI3.append('NaN')
    else:
        middleI3.append(i)
memberID['Middle'] = middleI3

In [12]:
#Cleaning up state
state1 = []
for i in messyState:
    if i[0] == '-':
        state1.append(i[1:])
    else:
        state1.append(i)
state2 = []
for i in range(len(state1)):
    if len(state1[i]) == 2:
        holder = state1[i][0] + ' ' + state1[i][:2][-1][:-1]
        #print(holder)
        state2.append(holder)
#         state2.append(state1[i][0])
#         state2.append(state1[i][:2][-1][:-1])
    else:
        state2.append(state1[i][0][:-1])
memberID['State'] = state2

In [13]:
#Image location style "https://bioguideretro.congress.gov/Static_Files/data/photo/M/M001197.jpg"
#xml data location "https://bioguideretro.congress.gov/Static_Files/data/S/S001141.xml"

In [14]:
memberID = memberID[['Member_ID', 'Last_Name', 'First_Name', 'Middle', 'State', 'Party']]

In [18]:
#memberID.to_csv('memberIDs_2.csv', index=False)

In [17]:
memberID

     Member_ID    Last_Name First_Name Middle         State       Party
0      A000009       Abdnor      James    NaN  South Dakota  Republican
1      A000014  Abercrombie       Neil    NaN        Hawaii  Democratic
2      A000017     Abourezk      James    NaN  South Dakota  Democratic
3      A000374      Abraham      Ralph    Lee     Louisiana  Republican
4      A000355      Abraham    Spencer    NaN      Michigan  Republican
...        ...          ...        ...    ...           ...         ...
2350   Z000018        Zinke       Ryan     K.       Montana  Republican
2351   Z000010         Zion      Roger     H.       Indiana  Republican
2352   Z000013     Zorinsky     Edward    NaN      Nebraska  Democratic
2353   Z000014       Zschau      Edwin     W.    California  Republican
2354   Z000016        Zwach       John     M.     Minnesota  Republican

[2355 rows x 6 columns]

In [18]:
ranking.head()

,Unnamed: 0,Party,Candidate,Last_Name,First_Name,State_Abbrv,Candidate_Votes,State,Total_Votes,lastName,Committee,Contributions,Election_Year,Assumed_Office
0,0,Democrat,Jack Reed,Reed,Jack,RI,223675,Rhode Island,316898,Reed,Armed Services,3960335,2014,1997
1,1,Democrat,Gary C. Peters,Peters,Gary,MI,1704936,Michigan,3121771,Peters,Homeland Security and Governmental Affairs,42543692,2019,2019
2,2,Democrat,Patrick J. Leahy,Leahy,Patrick,VT,192243,Vermont,320467,NaN,Appropriations,4770988,2016,1975
3,3,Democrat,Ron Wyden,Wyden,Ron,OR,1105119,Oregon,1952478,NaN,Finance,12628463,2016,1996
4,4,Democrat,Patty Murray,Murray,Patty,WA,1913979,Washington,3243317,NaN,"Health, Education, Labor and Pensions",13524088,2016,1993

In [23]:
len(ranking)

16

In [21]:
def findString(searchString, searchList):
    i = 0
    #searchString = 'McSally'
    while i < len(searchList):
        if searchList[i] == searchString:
            print(i)
            i+= 1
        else:
            i += 1
    return i

In [24]:
for i in memberID['Last_Name']:
    findString(i, ranking['lastName'])

6
6
6
6
6
6
6
6
6
8
14
10
12
13
9
11
1
1
0
0
7
5
15

In [ ]:
listNums2018_4=[31,80,110,116,118,9,65,3,36,24,54]
ranking2018 = votersLast2018.iloc[listNums2018_4, :]

In [19]:
chairs.head()

,Unnamed: 0,Party,Candidate,Last_Name,First_Name,State_Abbrv,Candidate_Votes,State,Total_Votes,Committee,Contributions,Election_Year,Assumed_Office
0,0,Republican,Pat Roberts,Roberts,Pat,KS,460350,Kansas,866191,"Agriculture, Nutrition and Forestry",8040544,2014,1997
1,1,Republican,James M. Inhofe,Inhofe,James,OK,558166,Oklahoma,820733,Armed Services,4841285,2014,1994
2,2,Republican,Michael B. Enzi,Enzi,Michael,WY,121554,Wyoming,171153,Budget,3772045,2014,1997
3,3,Republican,James E. Risch,Risch,James,ID,285596,Idaho,437170,Foreign Relations,2902855,2014,2009
4,4,Republican,Lamar Alexander,Alexander,Lamar,TN,850087,Tennessee,1374065,"Health, Education, Labor and Pensions",8201067,2014,2003